name: 'textlint Action'
description: 'This action allows you to proofread your text using textlint.'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - run: npx textlint -v
      shell: bash