name: 'textlint Action'
description: 'This action allows you to proofread your text using textlint.'
inputs:
  target:
    description: 'Text lint target'
    required: true
    default: '.'
  config:
    description: 'Text lint config'
    required: false
    default: ''
# outputs:
#   textlint-version:
#     description: 'The version of textlint'
#     value: ${{ steps.textlint.outputs.textlint-version }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: mv ${GITHUB_ACTION_PATH}/* .
      shell: bash
    - run: npx textlint -v
      shell: bash
    - run: npm ci
      shell: bash
    - run: pwd
      shell: bash
    - run: ls -la
      shell: bash
    - run: npx textlint --rule no-todo ${{ inputs.target }}
      shell: bash