name: 'textlint Action'
description: 'This action allows you to proofread your text using textlint.'
inputs:
  target:
    description: 'Text lint target'
    required: true
    default: '.'
  config:
    description: 'Text lint config'
    required: false
    default: ''
# outputs:
#   textlint-version:
#     description: 'The version of textlint'
#     value: ${{ steps.textlint.outputs.textlint-version }}
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/lint.sh
      shell: sh
      env:
        INPUT_TARGET: ${{github.workspace}}${{'/'}}${{ inputs.target }}